name: "Run Tests - Current"

on: [push]

jobs:
  Test:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs

      - name: Prepare Laravel Application
        run: |
            cp .env.example .env
            php artisan key:generate

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: php artisan test
